islands:
  "example-uuid":
    center:
      world: "world"  # The world where the island is located (must exist)
      x: 0.0
      y: 64.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
    size: 100
    minX: -50
    maxX: 50
    minY: 0
    maxY: 255
    minZ: -50
    maxZ: 50
    trusted: []  # List of UUIDs trusted to modify the island (empty by default)
    generator: 0