name: universe
version: ${project.version}
main: com.dragonsmith.universe.Universe
api-version: '1.21'  # Confirm the correct API version for your server

commands:
  createisland:
    description: Creates a new island at a random location for the player.
    usage: /createisland
    permission: universe.createisland
    permission-message: You don't have permission to create an island!

  expandisland:
    description: Expands the size of your island.
    usage: /expandisland
    permission: universe.expandisland
    permission-message: You don't have permission to expand your island!

  home:
    description: Teleports you to your island home.
    usage: /home
    permission: universe.home
    permission-message: You don't have permission to teleport to your island home!

  deleteisland:
    description: Deletes your island and removes it from the world.
    usage: /deleteisland
    permission: universe.deleteisland
    permission-message: You don't have permission to delete your island!

  upgradegenerator:
    description: Upgrades the ore generator on your island.
    usage: /upgradegenerator
    permission: universe.upgradegenerator
    permission-message: You don't have permission to upgrade your generator!

  setbiome:
    description: Set the biome for your island.
    usage: /setbiome <biome>
    permission: universe.setbiome
    permission-message: You don't have permission to set the biome!

  trust:
    description: Grants another player access to your island.
    usage: /trust <player>
    permission: universe.trust
    permission-message: You don't have permission to trust other players on your island!

  untrust:
    description: Grants another player access to your island.
    usage: /untrust <player>
    permission: universe.untrust
    permission-message: You don't have permission to untrust other players on your island!

  visit:
    description: Allows you to visit other people's islands.
    usage: /visit <player>
    permission: universe.visit
    permission-message: You don't have permission to visit other people's islands!
  ignoreclaims:
    description: Toggle ignoring island protection
    usage: /ignoreclaims
    permission: universe.ignoreclaims
  islandinfo:
    description: View your island's size, generator level, and trusted players
    usage: /islandinfo
  wand:
    description: Gives you the Mine Wand for selecting regions
    usage: /wand
    permission: universe.wand
    permission-message: You do not have permission.
  createmine:
    description: Create a new mine using your wand selection
    usage: /createmine <name>
    permission: universe.createmine
    permission-message: You do not have permission to create mines.
  resetmine:
    description: Resets a defined mine's interior.
    usage: /resetmine <ore|wood|nether>
    permission: universe.resetmine
    permission-message: You do not have permission to reset mines.
  setminespawn:
    description: Sets the respawn location for a mine.
    usage: /setminespawn <mine>
    permission: universe.setminespawn
    permission-message: You do not have permission to set mine spawn locations.
permissions:
  universe.island.modify:
    description: Allows players to bypass island protections and modify any island.
    default: op
  universe.createmine:
    default: op
    description: Allows staff to create mines using wand selection

  universe.island.bypass:
    description: Allows players to bypass all island restrictions (admin override).
    default: op

  universe.createisland:
    description: Allows players to create their own island.
    default: true

  universe.expandisland:
    description: Allows players to expand the size of their island.
    default: true

  universe.wand:
    default: op
    description: Allows staff to get and use the mine selection wand

  universe.home:
    description: Allows players to teleport to their island home.
    default: true

  universe.deleteisland:
    description: Allows players to delete their own island.
    default: true

  universe.upgradegenerator:
    description: Allows players to upgrade the ore generator on their island.
    default: true

  universe.setbiome:
    description: Allows players to change the biome of the island.
    default: true

  universe.trust:
    description: Allows players to grant access to their island to others.
    default: true

  universe.untrust:
    description: Allows players to remove access to their island to others.
    default: true

  universe.visit:
    description: Allows players to visit other people's islands.
    default: true
  universe.ignoreclaims:
    description: Allows bypassing island protections
    default: op
  universe.resetmine:
    description: Allows resetting mines.
    default: op
  universe.setminespawn:
    description: Allows the player to set the teleport location for a mine using /setminespawn.
    default: op